#!/bin/bash

#Parameters
SEQ=( 6 rawhide 15 16 17 )
SEQ_NUM=( 4 5 6 7 8 )
NAME_FIELD=f1
LINES_FIELD=f2
GITREV_FIELD=f3
SCRATCH_FIELD=f12
ENABLE_FIELD=f13
SLEEP_FAST=180
SLEEP_SLOW=10

TASK_COUNT=0
NUMBER_LINES=`head -n 1 $1 | cut -d "," -$LINES_FIELD`
TEMP_LINE=`head -n $NUMBER_LINES $1 | tail -n +2`

for n in $TEMP_LINE
do
    BUILD_ENABLE=`echo $n | cut -d "," -$ENABLE_FIELD`
    if [ "$BUILD_ENABLE" = "+" ]
    then
        NAME=`echo $n | cut -d "," -$NAME_FIELD`
        REV=`echo $n | cut -d "," -$GITREV_FIELD`
        for ((k=0; k < 5 ; k++))
        do
            STATE=`echo $n | cut -d "," -f${SEQ_NUM[$k]}`
            BUILD=${SEQ[$k]}
            if [[ "$STATE" = "-" && "$2" != "repo" ]]
            then
                SCRATCH=`echo $n | cut -d "," -$SCRATCH_FIELD`
                if [[ "$SCRATCH" = "-" || "$2" = "test" ]]
                then
                    TEST="test"
                else
                    TEST=""
                fi

                echo "Building $NAME $BUILD"
                ./koji_run $NAME $REV $BUILD $TEST

                if [ $TASK_COUNT -lt 3 ]
                then sleep $SLEEP_FAST
                else sleep $SLEEP_SLOW
                fi
                TASK_COUNT=`expr $TASK_COUNT + 1`
            elif [[ ("$STATE" = '+' || "$STATE" = 'b+') && "$2" = "repo"  ]]
            then
                REPONUM=`expr $k + 3`
                INREPO=`echo $n | cut -d "," -f$REPONUM`
                if [[ "$INREPO" = "-" ]]
                then
                    echo "$NAME not in repo $BUILD"
                fi
            fi
        done
    fi
done
