#!/bin/bash

#This script resize big images for my Android device

INPUT_FORMAT=JPG

if [ -z "$1" -o -z "$2" ]
then
    echo "repn: Format isn't correct!"
    echo "repn: Use conv_andr path_to_photos/ format number_of_threads"
    echo "where format - 480x320 or scaled"
    echo "Converted images will stored in path_to_photos/converted"
    echo "If number_of_threads not entered then using all system processors"
    exit
fi

if [ ! -e $1converted ]
then
    mkdir $1converted
fi

if [[ -z "$3" || $3 == 0 ]]
then
    THREADS=`cat /proc/cpuinfo | grep -c processor`
else
    THREADS=$3
fi
echo "Using $THREADS processors"

echo "convert -resize $2 "$1\$@" "$1converted/\$@"" > /tmp/conv_andr_tmp
ls -1 $1 | grep -i $INPUT_FORMAT | xargs -L1 -P$THREADS bash /tmp/conv_andr_tmp
rm -f /tmp/conv_andr_tmp
