#!/bin/bash

#crontab -e
#*/9 * * * * bash /home/vascom/Dropbox/github/scripts/dpms_switch
DPMS="dpms -display :0"

#Controlling browser
BROWSER=chrome
#Threshold of CPU utilisation by browser
THR=30

if [[ $HOSTNAME == milkyway.vascomdomain ]]
then 
    delim=","
else
    delim=","
fi

#Check monitor and dpms status
MONITOR_STATUS=`xset -display :0 q | grep "Monitor is" | awk '{print $3}'`
MONITOR_STATUS="On"
DPMS_STATUS=`xset -display :0 q | grep "DPMS is" | awk '{print $3}'`

if [[ "$1" == "manual" ]]
then
    if [[ "$DPMS_STATUS" == "Disabled" ]]
    then
        xset +$DPMS
    else
        xset -$DPMS
    fi
else
    #Check status of browser
    FLASH_STATE=`top -b -n 1 | grep $BROWSER -m 1 | awk '{print $9}' | cut -d "$delim" -f1`
    DATE=`date`
    echo "$DATE $FLASH_STATE $MONITOR_STATUS $DPMS_STATUS" >> /tmp/dpms_debug
    #echo $FLASH_STATE
    #echo $MONITOR_STATUS
    #echo $DPMS_STATUS
    if [ -n "$FLASH_STATE" ] && [ "$MONITOR_STATUS" = "On" ]
    then
        if [ "$FLASH_STATE" -gt "$THR" ]
        then
            if [[ "$DPMS_STATUS" == "Enabled" ]]
            then
                xset -$DPMS
#echo aa
            fi
        else
            if [[ "$DPMS_STATUS" == "Disabled" ]]
            then
                xset +$DPMS
            fi
        fi
    fi
fi
