#!/bin/bash

DPMS="dpms -display :0"

#Controlling browser
BROWSER=chromium
#Threshold of CPU utilisation by browser
THR=25

#Check dpms status
DPMS_STATUS=`xset -display :0 q | grep "DPMS is" | cut -d " " -f5`

if [[ "$1" == "manual" ]]
then
    if [[ "$DPMS_STATUS" == "Disabled" ]]
    then
        xset +$DPMS
    else
        xset -$DPMS
    fi
else
    #Check status of browser
    FLASH_STATE=`top -b -n 1 | grep $BROWSER -m 1 | awk '{print $9}' | cut -d "." -f1`
    echo $FLASH_STATE >> /tmp/dpms_debug

    if [ "$FLASH_STATE" != "" ]
    then
        if (( "$FLASH_STATE" > "$THR" ))
        then
            if [[ "$DPMS_STATUS" == "Enabled" ]]
            then
                xset -$DPMS
            fi
        else
            if [[ "$DPMS_STATUS" == "Disabled" ]]
            then
                xset +$DPMS
            fi
        fi
    fi
fi
