#!/bin/bash

#crontab -e
#*/9 * * * * bash /home/vascom/Dropbox/github/scripts/dpms_switch
DPMS="dpms -display :0"

#Controlling browser
BROWSER=chrome
#Threshold of CPU utilisation by browser
THR=15

if [[ $HOSTNAME == milkyway.vascomdomain ]]
then 
    delim=","
else
    delim=","
fi

#Check monitor and dpms status
ALL_STATUS=`xset -display :0 q`
MONITOR_STATUS=`echo "$ALL_STATUS" | grep "Monitor is" | awk '{print $3}'`
MONITOR_STATUS="On"
DPMS_STATUS=`echo "$ALL_STATUS" | grep "DPMS is" | awk '{print $3}'`

cpu_num=1
search_cpu=`top -n 1 -b | less | grep COMMAND`
for column in $search_cpu
do
    #echo $column $cpu_num
    if [[ "$column" == "%CPU" ]]
    then
        break
    fi
    cpu_num=`expr $cpu_num + 1`
done

if [[ "$1" == "manual" ]]
then
    if [[ "$DPMS_STATUS" == "Disabled" ]]
    then
        xset +$DPMS
    else
        xset -$DPMS
    fi
else
    #Check status of browser
    FLASH_STATE=`top -b -n 1 -o %CPU | grep $BROWSER -m 1 | awk "{print \$"$cpu_num"}" | cut -d "$delim" -f1`
    echo "`date` $FLASH_STATE a $MONITOR_STATUS b $DPMS_STATUS" >> /tmp/dpms_debug
    echo $FLASH_STATE
    #echo $MONITOR_STATUS
    #echo $DPMS_STATUS
    if [ -n "$FLASH_STATE" ] && [ "$MONITOR_STATUS" = "On" ]
    then
        if [ "$FLASH_STATE" -gt "$THR" ]
        then
            if [[ "$DPMS_STATUS" == "Enabled" ]]
            then
                xset -$DPMS
#echo aa
            fi
        else
            if [[ "$DPMS_STATUS" == "Disabled" ]]
            then
                xset +$DPMS
            fi
        fi
    fi
fi
