#!/bin/bash

#Reset color
Color_Off='\e[0m'       # Text Reset

#Colors
Red='\e[0;31m'          # Red
Green='\e[0;32m'        # Green

MY_PATH_FROM="/home/vascom/yandex.disk/.secure/"
MY_PATH_TO="/home/vascom/secure"

case "$1" in
    "-u")   fusermount -u $MY_PATH_TO
            ;;
    "-m")   if ! mount | grep $MY_PATH_TO 2>&1 > /dev/null
            then
                encfs $MY_PATH_FROM $MY_PATH_TO
            else
                echo "Directory already mounted."
            fi;;
    *)      echo -e "Give ${Green}-m${Color_Off} for mount or ${Green}-u${Color_Off} for unmount."
esac
