#!/bin/bash

#Convert data from Altera hex-file to decimal
hex_bits=12
max_bits=`echo "2^$hex_bits" | bc`
thr_bits=`echo "$max_bits/2-1" | bc`
suf_array="a b c d e f g h i j k l m n o p"

VRAM_H=`cut "$1" -c10,11,12,13 | head -n -1`
full_length=`wc -l "$1" | cut -d " " -f1`
full_length=`expr $full_length - 1`
split_lines=`expr $full_length / 16`

#Use octave for format conversion
if [ "$2" = "octave" ]
then
    echo "$VRAM_H" > vr

    echo "Use Octave with $hex_bits bit-width and $full_length numbers"
    octave -q --persist --eval "x = hex2dec(textread(\"vr\", \"%s\"));
        for k=1:$full_length if(x(k)>$thr_bits) x(k)=x(k)-$max_bits; end; end
        x_absfft = abs(fft(x));
        f=20*log10(x_absfft/max(x_absfft));"
    exit
fi

echo "$VRAM_H" | split -l $split_lines -

function convert_vram() {
    DATA_CONV=`cat $1`
    for DATA in $DATA_CONV
    do
        VRAM_D=`echo "ibase=16; $DATA" | bc`
        if [ "$VRAM_D" -gt $thr_bits ]
        then
            VRAM_D=`expr $VRAM_D - $max_bits`
        fi
        echo "$VRAM_D"
    done
}

for suf in $suf_array
do
    convert_vram xa$suf > xa${suf}_dec &
done

wait
cat xa[a-p]_dec
rm xa*
