#!/bin/bash

yd_remote_directory="/home/vascom/yandex.disk/"
gd_remote_directory="/home/vascom/google.drive/"
secure_section_from="/home/vascom/yandex.disk/.secure/"
secure_section_to="/home/vascom/secure"
yd_pid_file="/var/run/mount.davfs/home-vascom-yandex.disk.pid"
cd_pid_file="/var/run/chronyd.pid"
cronyd_delay=10

dev_sda1="/dev/disk/by-uuid/7a1bd51b-00d9-4c1c-88d0-9e987097af4e"
dev_sdb1="/dev/disk/by-uuid/acdb5d2e-3a7e-435f-ad53-e999a4723b51"
sda1_mountpoint="/home/vascom/sda1"
sdb1_mountpoint="/home/vascom/sdb1"
sda1_mounted="$sda1_mountpoint/downloads"

function secure_section() {
    if [ ! -e $secure_section_to/kva/ ]
    then
        echo -ne "Mount \e[31msecure\e[0m section? (Y/n) "
        read item
        case "$item" in
            y|Y|"") encfs $secure_section_from $secure_section_to
                ;;
            *) echo "Exit"
                ;;
        esac
    fi
}

function yandex_disk_check() {
    if [ ! -e $yd_remote_directory/Documents/ ]
    then
        if [ -e $yd_pid_file ]
        then
            sudo rm -rf $yd_pid_file
        fi
        sudo systemctl start home-vascom-yandex.disk.mount
    fi
    if systemctl status home-vascom-yandex.disk.mount &>/dev/null
    then
        echo -e "Yandex.Disk \e[32mOK\e[0m"
        secure_section
    else
        echo -e "yandex.disk mount \e[31mFAILED\e[0m"
    fi
}

function disks_mount_check(){
    if [ -e $dev_sdb1 ]
    then
        sudo mount $dev_sdb1 $sdb1_mountpoint
        echo "sdb1 mounted"
    fi

    if [ -e $dev_sda1 ]
    then
        if [ ! -e $sda1_mounted ]
        then
            sudo mount $dev_sda1 $sda1_mountpoint
            sudo mount --bind $sda1_mountpoint/downloads downloads/
#             sudo mount --bind downloads/ /var/www/lighttpd/downloads
#             sudo mount --bind downloads/ /var/ftp/downloads/
#             sudo mount --bind public_misc/ /var/www/lighttpd/misc/pictures/
            echo "sda1 mounted"
        else
            echo "sda1 already mounted"
        fi
    else
        echo -e "\e[31mError\e[0m: sda1 not connected"
    fi
    sudo mount --bind downloads/ /var/www/lighttpd/downloads
    sudo mount --bind downloads/ /var/ftp/downloads/
    sudo mount --bind public_misc/ /var/www/lighttpd/misc/pictures/
}

function google_mount(){
    if [ ! -e $gd_remote_directory/Documents/ ]
    then
        google-drive-ocamlfuse google.drive
        echo "Google.Drive mounted"
    else
        echo -e "Google.Drive \e[32mOK\e[0m"
    fi
}

function ftp_check(){
    ftp_status=`ps aux | grep pure-ftpd -c`
    if [ $ftp_status -lt 2 ]
    then
        sudo pure-ftpd -4 -c 10 -C 5 -i -l unix -p 50000:60000 -P vascom.myftp.org -S 8021 -B
    #     sudo pure-ftpd --ipv4only --maxclientsnumber 10 --maxclientsperip 5 --anonymouscantupload \
    #     -login unix --passiveportrange 50000:60000 --forcepassiveip vascom.myftp.org --bind 8021 --daemonize
        echo "FTP started"
    else
        echo -e "FTP \e[32mOK\e[0m"
    fi
}

function service_check(){
    if ! systemctl status $1 &>/dev/null
    then
        if [ "$1" == "chronyd" ]
        then
            sudo rm -f $cd_pid_file
            sudo systemctl restart chronyd
            echo "$1 restarted"
            sleep $cronyd_delay
        else
            sudo systemctl start $1
            echo "$1 started"
        fi
    else
        echo -e "$1 \e[32mOK\e[0m"
    fi
}

echo "Starting at temperature: `sensors | grep temp | cut -d "+" -f2`"

service_check chronyd
yandex_disk_check
google_mount
disks_mount_check
service_check noip
service_check nfs
service_check lighttpd
ftp_check

#fuse-zip -o allow_other russianfedora.pro.zip /var/www/lighttpd/misc/sites
#cd /var/www/lighttpd/misc/sites
#wget -r -k -l 4 -p -E -nc -np http://russianfedora.pro/logs/
