#!/bin/bash

function help_usage() {
    echo -e "Format isn't correct!"
    echo -e "Use \e[1;30mkoji_run build project_name commit_number dist_number\e[0m to build package"
    echo -e "Use \e[1;30mkoji_run regen dist\e[0m to repos regen"
    echo -e "Use \e[1;30mkoji_run add-pkg project_name owner dist1 dist2 dist3 \e[0m to add package"
    exit
}

if [ -z "$1" -o -z "$2" ]
then
    help_usage
fi

koji_config="/etc/koji-rf.conf"

function dist_expand() {
    case $1 in
        [67])       dist="dist-el$1";;
        rawhide)    dist="dist-rfr-rawhide";;
#        23)         dist="dist-rfr$1-devel";;
        *)          dist="dist-rfr$1";;
    esac
}
# dist_expand $3
# echo "koji $5 -c $koji_config build $4 $dist git://github.com/RussianFedora/$1.git?#$2"
case $1 in
    "regen")
        dist_expand $2
        koji -c $koji_config regen-repo $dist-build;;
    "add-pkg")
        args=("$@")
        args_n=`expr $# - 1`
        echo -en "Added $2 to "
        for i in `seq 3 $args_n`
        do
            dist_expand ${args[$i]}
            echo -en "${args[$i]} "
            koji -c $koji_config add-pkg $dist $2 --owner=$3
        done
        echo -en "\n";;
    "build")
        if [ -z "$4" ]
        then
            echo "Need first dist_number"
        else
            dist_expand $4
            #echo "koji -c $koji_config build $5 $dist git://github.com/RussianFedora/$2.git?#$3 1>/dev/null"
            koji -c $koji_config build $5 $dist git://github.com/RussianFedora/$2.git?#$3 1>/dev/null &
        fi;;
    *)
        help_usage;;
esac
