#!/bin/bash

if [ -z "$1" -o -z "$2" ]
then
    echo "Format isn't correct!"
    echo "Use koji_run project_name commit_number dist_number"
    echo "Use koji_run regen number for repos regen"
    exit
fi

if [ "$3" = "16" ]
then
    DIST="-alpha$3"
else
    DIST="$3"
fi

if [ "$1" = "regen" ]
then
    koji regen-repo dist-rfr$DIST-build
    exit 0
fi

if [[ -z "$4" || "$4" -le "0" || "$4" = "quiet" ]]
then
    if [[ -z "$3" || "$3" -le "0" ]]
    then
        echo "Need first DIST_NUMBER"
    else
        koji build dist-rfr$DIST git://github.com/RussianFedora/$1.git?#$2 &>/dev/null &
    fi
fi
