#!/bin/bash
word=$1

for i in `seq 0 1048575`
do
   bin=`echo "ibase=10; obase=2; $i" | bc`
   sum=`echo $bin | sed -e 's/./+&/g' -e 's/^\+//' | bc`
#     echo "$sum"
   echo "    20'd$i    : out = 5'd$sum;"
done

# for i in `seq 0 15`
# do
#     echo -e "$word[$((5+$((i*40))-1)):$((i*40))]+$word[$((10+$((i*40))-1)):$((i*40+5))]+$word[$((15+$((i*40))-1)):$((i*40+10))]+$word[$((20+$((i*40))-1)):$((i*40+15))]\
# +$word[$((25+$((i*40))-1)):$((i*40+20))]+$word[$((30+$((i*40))-1)):$((i*40+25))]+$word[$((35+$((i*40))-1)):$((i*40+30))]+$word[$((40+$((i*40))-1)):$((i*40+35))]+"
# done
