#!/bin/bash

if [ -z "$1" -o -z "$2" ]
then
    echo "Format isn't correct!"
    echo "Use renswap first_file second_file"
    exit
fi

if [ ! -e "$1" ]
then
    echo "Source file does not exist"
    exit
fi

mv "$1" "$1.renswaptmp"
if [ -e "$2" ]
then
    mv "$2" "$1"
else
    echo "File "$2" does not exist, file "$1" will be blank"
    touch "$1"
fi
mv "$1.renswaptmp" "$2"
