#!/bin/bash

if [ -z "$1" -o -z "$2" -o -z "$3" ]
then
    echo "repn: Format isn't correct!"
    echo "repn: Use repn N1 N2 file"
    echo "repn: where N1 - the first number in file"
    echo "repn:       N2 - the final number"
    exit
fi

if [ -f $3 ]
then :
else
    echo "File $3 doesn't exist"
    exit
fi

PAR=$1
MAX=$2

while [ $PAR -le $MAX ]
do
    sed "s/CLK_FOR_TESTNUM/CLK_FOR_TEST_$PAR/g" $3 > /tmp/tmpr1.txt
    sed -i "s/parallelNUM/parallel_$PAR/g" /tmp/tmpr1.txt
    sed -i "s/parallel_impNUM/parallel_imp_$PAR/g" /tmp/tmpr1.txt
    sed -i "s/NUM/[$PAR]/g" /tmp/tmpr1.txt
    PAR=`expr $PAR + 1`
    cat /tmp/tmpr1.txt >> /tmp/tmpr2.txt
done
mv /tmp/tmpr2.txt test.txt
rm /tmp/tmpr1.txt
