#!/bin/bash

#Check
START_USER=`whoami`

if [ $START_USER == "root" ]
then
    if [ ! -e /tmp/vb_rebuild ]
    then
        mkdir /tmp/vb_rebuild
    fi
    echo "Mounting Guest Addititions ISO"
    mount /dev/sr0 /tmp/vb_rebuild
    /tmp/vb_rebuild/VBoxLinuxAdditions.run
    echo "Unmounting Guest Addititions ISO"
    umount /tmp/vb_rebuild
    rm -rf /tmp/vb_rebuild
else
    echo "You must be root to run this script"
fi
