#!/bin/bash

#Check
START_USER=`whoami`

if [ $START_USER == "root" ]
then
    if [ ! -e /tmp/vb_rebuild ]
    then
        mkdir /tmp/vb_rebuild
    fi
    mount /dev/sr0 /tmp/vb_rebuild
    /tmp/vb_rebuild/VBoxLinuxAdditions.run
else
    echo "You must be root for run this script"
fi
