#!/bin/bash

a=( 3 10 15 32 50 75 )
b=( 1278000 4260000 6205000 12600000 21000000 36000000 )
c=( 1000 6500 16500 56000 270000 500000 )
d=( 202500 1408000 32800000 13200000 60000000 126000000 )

function compute() {
    if [[ "$1" == DEF ]]
    then
        local m=( "${b[@]}" )
        local n=( "${a[@]}" )
        local LIMIT=${#a[@]}
        for ((k=0; k < $LIMIT ; k++))
        do
            local n1[$k]=`expr ${n[$k]} \* 1000`
        done
    else
        local LIMIT=${#c[@]}
        local m=( "${d[@]}" )
        local n=( "${c[@]}" )
        local n1=( "${c[@]}" )
    fi


    for ((k=0; k < $LIMIT ; k++))
    do
        local PRE[$k]=`expr "${m[$k]}" / "${n1[$k]}"`
    done

    local MIN_PRE=${PRE[0]}

    for ((k=1; k < $LIMIT ; k++))
    do
        if [ ${PRE[$k]} -lt $MIN_PRE ]
        then
            MIN_PRE=${PRE[$k]}
        fi
    done

    for ((k=0; k < $LIMIT ; k++))
    do
        if [ $MIN_PRE -eq ${PRE[$k]} ]
        then
            echo -e "$1: ${n[$k]} \tPrice ${m[$k]} \t P ${PRE[$k]}"
            local K_MIN=$k
        fi
    done

    if [ $K_MIN -eq "0" ]
    then
        local MIN_POS=${PRE[1]}
    else
        local MIN_POS=${PRE[0]}
    fi

    for ((k=0; k < $LIMIT ; k++))
    do
        if [ $k -ne $K_MIN ]
        then
            if [ ${PRE[$k]} -lt $MIN_POS ]
            then
                MIN_POS=${PRE[$k]}
            fi
        fi
    done

    for ((k=0; k < $LIMIT ; k++))
    do
        if [ $MIN_POS -eq ${PRE[$k]} ]
        then
            echo -e "Second: ${n[$k]} \tPrice ${m[$k]} \t P ${PRE[$k]}"
        fi
    done
}

compute DEF

compute POW
