#!/bin/bash

#crontab -e
#0 */1 * * * bash /home/vascom/Dropbox/github/scripts/yandex_sync
if [ -z "$1" ]
then
    local_directory="/home/vascom/local.yandex.disk/"
else
    local_directory="$1"
fi
remote_directory="/home/vascom/yandex.disk/"


if [ -e $remote_directory/Documents/ ] && [ -e "$local_directory" ]
then
    rsync -azsS --delete "$remote_directory" "$local_directory"
#else
    #echo "Yandex.disk not mounted yet."
    #sudo mount yandex.disk
fi
