#!/bin/bash

if [ -e /home/vascom/yandex.disk/Documents/ ]
then
    rsync -azsS --delete /home/vascom/yandex.disk/ /home/vascom/yandex.disk.local/
#else
    #echo "Yandex.disk not mounted yet."
    #sudo mount yandex.disk
fi
